### ISSUE TITLE
set_time_limit exception

### ISSUE THREAD

**Issue by Herokid** [yiisoft/yii-web#1]
This line fail when is not possible change max_execution_time (secure mode on shared hosting).
https://github.com/yiisoft/yii-web/blob/e9a332819a2d911c83fe7be3bcc9075b04e5b7ae/src/Response.php#L431

this is the Exception:
`2018-07-17 17:49:57 [79.152.50.37][1][5a0d110aa5700ad29f45e00b218e02a6][error][yii\base\ErrorException:2] yii\base\ErrorException: set_time_limit() has been disabled for security reasons in /vendor/yiisoft/yii2/web/Response.php:419
Stack trace:
#0 /vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(2, 'set_time_limit(...', '/usr/home/affor...', 419)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'set_time_limit(...', '/usr/home/affor...', 419, Array)
#2 /vendor/yiisoft/yii2/web/Response.php(419): set_time_limit(0)
#3 /vendor/yiisoft/yii2/web/Response.php(340): yii\web\Response->sendContent()
#4 /usr/home/affordablemallorca.com/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Response->send()
#5 /usr/home/affordablemallorca.com/web/index.php(21): yii\base\Application->run()
#6 {main}
2018-07-17 17:49:56 [79.152.50.37][1][5a0d110aa5700ad29f45e00b218e02a6][info][application] $_GET = [
    'p' => 'admin/actions/assets/thumb'
    'uid' => '5688258a-a695-4d6f-b1b1-428e8d06b8e8'
    'width' => '60'
    'height' => '60'
    'v' => '1531837664'
]`

I had to comment on the line in the project where I have the problem.
Thanks in advance and sorry for my english.

**Comment by hiqsol** [comment]
This is package is in early stage of development and not intended for use yet.
Please use `yiisoft/yii2` package for the moment.

**Comment by Herokid** [comment]
Ok, thanks @hiqsol
