### ISSUE TITLE
Implement flash messages

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#100]
Flash messages service should be separate from Session but use session internally.

Logic could be ported from Yii 2.

See https://github.com/yiisoft/yii-web/issues/31

**Comment by pchapl** [comment]
I think we should also provide default usage of this service (like `Alert` widget in [Yii2](https://github.com/yiisoft/yii2-app-basic/blob/master/widgets/Alert.php) app), but I'm not sure in which package it should be. [yii-demo](https://github.com/yiisoft/yii-demo)?

**Comment by samdark** [comment]
yii-demo would be fine for now.
