### ISSUE TITLE
Implement authentication middleware

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#114]
- Should be Middleware
- https://github.com/yiisoft/yii2/tree/master/framework/filters/auth

**Comment by samdark** [comment]
@rustamwin do you plan helping with it?

**Comment by rustamwin** [comment]
Yes

**Comment by rustamwin** [comment]
But it should be here? not in yii-rest

**Comment by samdark** [comment]
We can extract these into `auth` package later.

**Comment by samdark** [comment]
Implementation is done by @rustamwin. What's left:

- [ ] Tests.
- [ ] Considering if moving code to separate package worth it.

**Comment by rustamwin** [comment]
Oh. Should we also add [`JWT`](https://github.com/yiisoft/yii-web/issues/23) method?

**Comment by samdark** [comment]
Which third party package?

**Comment by rustamwin** [comment]
https://github.com/firebase/php-jwt

**Comment by samdark** [comment]
Isn't it abandoned?

**Comment by rustamwin** [comment]
Looks like yes https://github.com/firebase/php-jwt/issues/247
I think we can do it in own package

**Comment by demonking** [comment]
>     * Considering if moving code to separate package worth it.

Should we? Since yii-web is a requirement for yii-rest?

**Comment by demonking** [comment]
> Looks like yes [firebase/php-jwt#247](https://github.com/firebase/php-jwt/issues/247)
> I think we can do it in own package

I have used this Library in some projects.
https://github.com/RobDWaller/ReallySimpleJWT

There's also a psr7/psr15  version :

https://github.com/RobDWaller/psr-jwt

**Comment by samdark** [comment]
> So yii-rest would depend on yii-web and yii-auth, but yii-auth also depends on yii-web

That's not circular dependency so should not cause any issues.

**Comment by demonking** [comment]
That's not the problem , i mean, is it really neccessary to split it into a separate package ? 

The Authentification Classes are made for web applications .

**Comment by samdark** [comment]
If "rest" would depend on "web" then no, it's not really necessary.

**Comment by demonking** [comment]
That's the question, i have only looked into the composer.json from yii-rest and though this was planned :)

But when you go from the point, that we will implement jwt etc, then i would prefer to separat it, because this would bloating yii-web .

When it's ok, i will write the test's @rustamwin i will have some time the following weeks

**Comment by samdark** [comment]
@demonking tests would be very helpful, thanks. It's not decided yet about `yii-rest` dependencies yet.

**Comment by demonking** [comment]
Seems like @zhukovra has finished it before me #140

**Comment by samdark** [comment]
You still can join to review/improve it.

**Comment by samdark** [comment]
Tests done in #140

**Comment by rustamwin** [comment]
@samdark it looks alive https://github.com/lcobucci/jwt

**Comment by rustamwin** [comment]
> We can extract these into auth package later

Could you do it? `auth`, `auth-jwt`

**Comment by samdark** [comment]
Created two repos and a ticket.
