### ISSUE TITLE
ucwords header name

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#121]
### What steps will reproduce the problem?

I think it's unnecessary to convert the first letters of the words to uppercase.

https://github.com/yiisoft/yii-web/blob/11a354d8542de7f5b4d0378b321f1226d5223f93/src/ServerRequestFactory.php#L143

This solution also causes quite a few unnecessary conversions instead of simply `strtolower()` conversions.

HTTP2 use only lower case: https://tools.ietf.org/html/rfc7540#section-8.1.2

### What is the expected result?

`HTTP_X_FORWARDED_FOR` -> `x-forwarded-for`

### What do you get instead?

`HTTP_X_FORWARDED_FOR` -> `X-Forwarded-For`

| Q                | A
| ---------------- | ---
| Version          | 1.0.0-under development
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
It is done to be closer to specifications. See

- https://tools.ietf.org/html/rfc7231#section-3.1.1.5
- https://tools.ietf.org/html/rfc7239#section-4

These are all ucworded.

**Comment by samdark** [comment]
But since HTTP 1.1 is case insensitive and HTTP/2 requires lowercase, it makes sense to actually lowercase these.

**Comment by samdark** [comment]
Good catch!
