### ISSUE TITLE
Middleware/IpFilter is very limited

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#123]
### What steps will reproduce the problem?

Even with basic usage, I need the following:
- checking more than one IP (IPv4 + IPv6)
- action type of filter: allow or deny
- IP address for checking (remote address, user IP)

### What is the expected result?

```php
(new IpFilter($this->responseFactoryMock))
  ->withIpMatch('127.0.0.1', '::1', '10.2.0.0/16')
  ->withIp($request->getNetworkResolver()->getUserIp());
```

### What do you get instead?

- action type: only allow
- ip address for checking: remote address
- check one IP

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.0-under-development
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
> IP address for checking (remote address, user IP)

Can't be done without having https://github.com/yiisoft/yii-web/issues/119

The rest sounds fine.
