### ISSUE TITLE
Middleware implements the action, which does limit the logic.

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#124]
### What steps will reproduce the problem?

Currently, middleware contains logic, which is difficult to redefine and to vary. For example, at `IpFilter`, I want to redirect (either internal or external).

### What is the expected result?

I would delegate middleware functions to a `Match` class.

```php
new Match(new Csrf())->notMatch(new CsrfFail());
new Match(new Csrf())->notMatch(new HttpRedirect('/invalid-csrf', 302));

new Match((new IpFilter())->withIpMatch('127.0.0.1'))->notMatch(new HttpForbidden())
new Match((new IpFilter())->withIpMatch('127.0.0.1'))
  ->notMatch(new InternalRedirect('/security/access-denied', ['param' => 2222]));

// I don't know an example, but it could also happen:
new Match(...)->match(...)->notMatch(...);

// hard case
new Match(new Any(
  new Csrf(),
  (new IpFilter)->withIpMatch('127.0.0.1')
))->notMatch(new HttpBadRequest());
```

### What do you get instead?

https://github.com/yiisoft/yii-web/blob/3398f9b5ccdeea2365d51f62498f4e1ce03910a8/src/Middleware/IpFilter.php#L31-L33

https://github.com/yiisoft/yii-web/blob/3398f9b5ccdeea2365d51f62498f4e1ce03910a8/src/Middleware/Csrf.php#L36-L42

| Q                | A
| ---------------- | ---
| Version          | 1.0.0-under-development
| PHP version      | -
| Operating system | -

**Comment by kamarton** [comment]
Even better:

```php
class Csrf extends MatchMiddleware
{
  function __construct() {
    $this->notMatch(
       new ResponseStatus(400),
       new ResponseContent('Unable to verify your data submission.')
    );
    // or
    $this->notMatch(new CsrfFail());
  }
}

new Csrf();   // normal case

// with override
new Csrf()->notMatch(
  new ResponseStatus(400),
  new Route('/error/csrf-error'),
  (new LogRequest())->withData()
);
// or
new Csrf()->notMatch(
  new CsrfFail(),
  new Route('/error/error-page',['type' => 'csrf']),
  (new LogRequest())->withData()
);

```

**Comment by samdark** [comment]
Some degree of flexibility won't hurt but I don't like to introduce inheritance from `MatchMiddleware`. The logic in it is simple `if` and callback execution. No need to extract it.

For CSRF middleware it makes no sense to behave differently in case of failure to verify code.

IpFilter customization is OK but let's create a separate issue about that.

**Comment by kamarton** [comment]
For more comment on CSRF:
Yii2 allowed us to elegantly inform the user in the event of a CSRF error. And what's more, it made it possible to run even more important tracking code (eg google analytics).

Obviously, in most cases, it is attack (empty or not exists the CSRF), but for an incorrect configuration, the end user is not necessarily wrong (eg `validationKey` is not filled in and always generates a new one during init deployment). In extreme cases, the framework may also have an bug.

![Bad Request   Shardimage com](https://user-images.githubusercontent.com/9432032/66695715-3a292c00-ecc5-11e9-8eee-fc60b0ce91c6.png)

**Comment by samdark** [comment]
OK. It makes sense but let's keep these separate. One case - one issue.
