### ISSUE TITLE
Decoupling - User Id string assumption

### ISSUE THREAD

**Issue by ptheofan** [yiisoft/yii-web#126]
I totally love the way Yii3 unfolds so far. After digging a bit around I came across this assumption - that user-id is a string. 

https://github.com/yiisoft/yii-web/blob/3398f9b5ccdeea2365d51f62498f4e1ce03910a8/src/User/IdentityRepositoryInterface.php#L6

https://github.com/yiisoft/yii-web/blob/3398f9b5ccdeea2365d51f62498f4e1ce03910a8/src/User/IdentityInterface.php#L10

Whilst it is true that anything can be converted to a string (even going as far as serialise/unserialize) wouldn't it be prudent to play safe and have some Interface represent a user id which exposes a function that can return a text version (for convenience and to counter the limitation of php to hashtable keys to handle objects).

This way, we always transfer around a pointer to an object which can be modified to any extent needed for any purpose.

something like the ActorInterface I also proposed [here](https://forum.yiiframework.com/t/improving-the-rbac-to-accommodate-a-wider-range-of-popular-use-cases/123539/9)

**Comment by rob006** [comment]
What is the point of introducing `ActorInterface` if its main purpose is returning string? It does not change anything, since at the end you will need to represent user ID as string anyway (all implementations require string ID).

> This way, we always transfer around a pointer to an object which can be modified to any extent needed for any purpose.

That sounds like a drawback, not feature.

**Comment by ptheofan** [comment]
> What is the point of introducing `ActorInterface` if its main purpose is returning string? 

The main purpose is not returning a string. The only reason it has that function is to for when you need a string to use in hashmaps since php does not support objects as keys.

```php
$map[$obj->getGuid()] = $obj;
```

The simplest example I can think of is MongoID. The ID of a Mongo document is an Object. Now given this is in the heart of the framework and it should be DB agnostic it kinda means string is a bad choice, especially when it's type-coupled.

**Comment by rob006** [comment]
> With regard to RAD yes, this is a drawback. With regard to enterprise-level apps this is fundamentals.

There is exactly the opposite. You may control implicit mutations in small projects, but this is fundamental drawback for enterprise-level application. The bigger application is, the harder is to control mutability. 

> Considering this is in the heart of the web framework I would suggest making it use-case agnostic.

Having ID expressed as universal type **is** use-case agnostic. There are cases where object will not be accepted (like ID saved in database), having API which will express user ID in different ways is just unnecessary complication, which does not solve anything.

**Comment by ptheofan** [comment]
> There are cases where object will not be accepted (like ID saved in database)

Exactly. There's no one type fits all. Thus the agnostic approach.
Here's another very simple example even with MySQL. Assume your user PK is composite and it consists of 3 columns (INT, VARCHAR, ENUM).
How will you represent this as UserId?

**Comment by rob006** [comment]
>  How will you represent this as UserId?

`json_encode()` - it is universal and you need to support it anyway (string ID is required by interface proposed by you). 

You're proposing representing ID both as string and object. This may create situations where `$isA === $idB` will return `false`, even if they're the same ID, but with different representation (one is string and second is object).

**Comment by ptheofan** [comment]
> json_encode() - it is universal and you need to support it anyway (string ID is required by interface proposed by you).

`json_encode` is very expensive. I don't want to have to `json_encode` and `json_decode` the ID every time they have to go through a function that needs the UserID

1. `json_encode` is far more expensive than the implementation designed exactly as needed to fit the particular class.
1. The object can internally cache and reuse an already computed GUID
1. `json_encode` will return a **json**, not a GUID.
1. The `getGUID(): string` is there only enforce the implementation of `__toString()` and output a well-formatted string representation (computationally expensive similar to json_encode thus called only when needed to get access to a single string representation and not everytime I need to pass it through functions internally).
1. The the GUID I can also use in URLs (see AWS/Azure/Amazon/Google/Windows... GUIDs are everywhere and they're not JSON for very good reasons).


> You're proposing representing ID both as string and object.

No, on the contrary. I represent an ID as an object that encapsulates the necessary functionality.
1. Using an internal function the object itself can even cache it and reuse it.

> This may create situations where $isA === $idB will return false

This is **not a good way to compare objects** in the first place. Unlike in the arrays, in objects, the `===` operator tests if they have the same base address (literally same instance) not if the attributes (what the object represents) are the same.

**Comment by samdark** [comment]
@ptheofan having `toString()` in your class representing ID is fine but I see no benefit of `IdentityInterface` being aware of it. In your concrete implementation of `getId()` you can call `toString()` on your identity object:

```php
class MongoIdentity implements IdentityInterface
{
    // ...

    public function getId()
    {
        return $this->mongoId->toString();
    }
}
```

When calling `findIdentity()` you can do it as well:

```php
$identity = $identityRepository($mongoId->toString());
```

**Comment by rob006** [comment]
> `json_encode` is very expensive. I don't want to have to `json_encode` and `json_decode` the ID every time they have to go through a function that needs the UserID

Why would you need to `json_decode()` an ID? If you use it as actual ID, you need to compute it once and use it as identifier without further processing. If you want to extract some data from ID, that means that you're trying to use ID as DTO. 

>  GUIDs are everywhere and they're not JSON for very good reasons

I know - they're already strings, so there is no need to convert them to JSON. I'm guessing that there is a good reason why they're not objects. ;)

> This is **not a good way to compare objects** in the first place.

But it is the best way to compare strings. It only becomes a problem when you try to introduce alternative way of representing ID as an object.

BTW: using `==` for comparing objects is not good idea either: https://3v4l.org/9YQq6

**Comment by ptheofan** [comment]
> BTW: using == for comparing objects is not good idea either: https://3v4l.org/9YQq6

I never said it is. Using `==` is as bad as `===`. To really compare objects you need to implement the [`Comparable`](https://wiki.php.net/rfc/comparable#concerns) interface and implement the function.

> Why would you need to json_decode() an ID? If you use it as actual ID, you need to compute it once and use it as identifier without further processing. If you want to extract some data from ID, that means that you're trying to use ID as DTO.

I need it as an object because I want to access each attribute independently. They obviously have a meaning and are not there just to look complex. Thus every time that object passes through a function that implements $userID as string it needs to get decoded again and again.

```
So by enforcing $userID to be a string you end up to this...

User::can($userIdAsString)
AccessChecker($userIdAsString... decompose, check stuff, prepare stuff, send it to the permissions...)
Permission($userIdAsString... decompose, check stuff...., send to rule)
Rule($userIdAsString... decompose, check stuff....)
```

**Comment by rob006** [comment]
> I need it as an object because I want to access each attribute independently.

That means that you don't need an ID - you need a DTO. Expecting DTO where you should have ID may suggest architectural problem and lack of real ID in your system (natural keys are tricky, but composite natural keys are just nightmare).

**Comment by ptheofan** [comment]
> That means that you don't need an ID - you need a DTO.

Music to my ears.

> Expecting DTO where you should have ID may suggest architectural problem and lack of real ID

or complex PK

> composite natural keys are just nightmare

*Objection; Opinion*. Composite keys can be tricky sometimes. Especially when someone is jumping between implementations like Postgres to MySQL or to MSSQL etc, but that's all.

> may suggest architectural problem

*Objection; Speculation*. 

In a multi-account system, all permissions are checked against the user and account because the same user has different privileges per account.

In Yii2 you can either
1. pass the account-id as a param (and forget caching because... `Manager` will not cache the result if params are used) not to mention in that context the use of `Assoc` array is prone to errors.
1. or pass the account-id combined with the user-id as a string and 'explode' it again and again in every function (because you do need that account-id and user-id separately)
1. or as an Object (DTO to the rescue).

From my perspective; I honestly don't see the added complexity in turning the String into an interface. But as a String... I can see LINT already complaining when passing that `id INT` from the `ActiveRecord` in there

```php
function x(string $s) {
    echo $s;
}

x(1);
   ~----> Not a string!
```

Considering the pros and cons when it comes to complex keys;


*With String*
1. Simplicity
1. Easy to debug
1. Hard to make changes
1. High risk of breaking things when working in larger teams

*With Object*
1. Simplicity
1. Easier to debug
1. Easy to make changes
1. Type hinting and finding all occurrences is as simple a right-click away.

**Comment by kamarton** [comment]
> Objection; Opinion. Composite keys can be tricky sometimes. Especially when someone is jumping between implementations like Postgres to MySQL or to MSSQL etc, but that's all.

Even in hard use it is advisable to generate a string key, either from a record (eg composite keys) or a randomly generated string.

> High risk of breaking things when working in larger teams

How do you transfer an object to another developer? eg. with chat application. 
The string can be easily transferred at any time through chat, email, screenshots, etc.

**Comment by samdark** [comment]
Re-read whole issue thread and decided to keep ID as string. While I understand benefits of having ID as object, strings is:

1. Simpler.
2. Usual design of the storage.
3. If we're talking about strict domain driven design, this one is part of the infrastructure layer so it's actually done by the book (IDs shouldn't make their way into domain layer but using them in infrastructure layer is fine).
