### ISSUE TITLE
Separation of `x-resolver-url` from NetworkResolver

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#141]
### What steps will reproduce the problem?

In yii2, the `Request` class handled` X-Rewrite-Url`. In Yii3 this would be equivalent to `NetworkResolver`, but since it is a special case and can be generalized, I would recommend a separate middleware.

https://github.com/yiisoft/yii2/blob/c5f7704a4d515f06efa66a94940db3aa24d02f6c/framework/web/Request.php#L1030-L1033

### What is the expected result?

```php
new UrlRewriteFromHeader()    // default x-rewrite-url
  ->withHeaders(['x-custom-header'])  // override with any header
```

| Q                | A
| ---------------- | ---
| Version          | 3.0.x
| PHP version      | -
| Operating system | -

**Comment by kamarton** [comment]
related to #6

**Comment by samdark** [comment]
Why should it be separate from NetworkResolver? It seems to be the same logic for all rewrite-headers regarding to when to apply these.

**Comment by kamarton** [comment]
> Why should it be separate from NetworkResolver?

- Unnecessarily complicated configuration parameters for `NetworkResolver`.
- It should be built into all `NetworkResolver` (code redundancy).
- There may be cases where you only need to change the URL, using `NetworkResolver` is unnecessary.

**Comment by samdark** [comment]
> There may be cases where you only need to change the URL, using NetworkResolver is unnecessary.

Then networkresolver should be configurable. It is necessary since the logic of trusting or not trusting `X-Forwarded-` headers is the same and is based on IPs of servers chain.

**Comment by kamarton** [comment]
> Then networkresolver should be configurable. It is necessary since the logic of trusting or not trusting X-Forwarded- headers is the same and is based on IPs of servers chain.

Like `yii2`, `ThrustedHostsNetworkResolver` enables you to remove or retain secure headers. If the source is unsafe (header is removed), the `UrlRewrite` middleware in the chain does not modify the request.
And if the source is safe at all times (because it is validate by the web servers before it, etc.), then `UrlRewrite` can be used with complete peace of mind, especially if it is known that it is always needed.

**Comment by samdark** [comment]
Isn't it NetworkResolver that determines if host is safe?

**Comment by kamarton** [comment]
> Isn't it NetworkResolver that determines if host is safe?

Only when necessary. If necessary, it will detect and remove not trusted headers or define the IP as needed.

**Comment by kamarton** [comment]
The main problem is that this is a bit of a special case. This makes NetworkResolver complicated. However, it can be used as a middleware for everything. #6 ticket also felt a bit that this case should be treated separately. But obviously can start by inserting it into `NetworkResolver` and deciding on it in alpha version if necessary.

**Comment by samdark** [comment]
I'd start with putting it into `NetworkResolver`. There are only three commonly used headers: X-Forwarded-For, X-Forwarded-Host and X-Forwarded-Proto. Plus their standardized Forwarded version.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded
