### ISSUE TITLE
SapiEmitter: missing whitespace before `Reason-Phrase` if empty string (HTTP status line)

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#142]
### What steps will reproduce the problem?

As described in https://tools.ietf.org/html/rfc2616#section-6.1, a space must precede `Reason-Phrase`, even if it is an empty string.

> Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF

https://github.com/yiisoft/yii-web/blob/a88d7fd6d6a2b9893e461134bf4472b70ddbe313/src/Emitter/SapiEmitter.php#L31-L36

### What is the expected result?

`HTTP/1.1 400` + SPACE

### What do you get instead?

`HTTP/1.1 400`

### Additional info

This does not seem logical at all, but it is advisable to test whether this can cause a problem with or without repair.

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
Fixed. Good catch 👍
