### ISSUE TITLE
ErrorCatcher Instead of the container use object property

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#143]
### What steps will reproduce the problem?

Currently, it retrieves the renderer from the container, which results in a more difficult process than the `ErrorCatcher` itself stores the renderer objects.

### What is the expected result?

```php
[
  ...
  // middlewares
  (new ErrorCatcher(...))->withRenderer(
    'x/myformat',
    (new MyFormatRenderer())->setStyle(...pretty)->set...(...) 
  ),
  ....
]
```

### What do you get instead?

```php
// Somewhere in the code.
$container->set(MyFormatRenderer::class, new MyFormatRenderer()...);

[
  ...
  // middlewares
$errorCather = (new ErrorCatcher())
  ->withRenderer('x/myformat', MyFormatRenderer::class),         // currently not implemented
  ....
]
```

### Additional info

The current solution allows to override the renderer when have access to the container. The proposed solution also provides this functionality, e.g. simply storing the `ErrorCatcher` object in the container.

| Q                | A
| ---------------- | ---
| Version          | 3.0.x
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
Decision on making it like it is now was because:

1. There's no need to instantiate error rendered before there is an error.
2. There's no need to instantiate all error renderers at once.

As for adding your own renderer, a method could be added on request.
