### ISSUE TITLE
ErrorCatcher for images with1x1 empty gif

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#146]
### What steps will reproduce the problem?

If the response type is image, render a 1x1 transparent gif in case of error. Error details should be inserted as HTTP headers.

### What is the expected result?

```php
$errorCatcher->withAddedRenderer('image/*', EmptyGifRenderer::class);
```

### What do you get instead?

Not implemented so I will get some text page instead of image.

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
Why headers? For an image the only way to view the error is to inspect response i.e. go to networking panel in a browser and see what's there. It is equal for both headers and body in this regard, isn't?

**Comment by kamarton** [comment]
If the response does not return an image, then design problems occur. (Depend on browser)

Example in firefox with 500 status code and HTML:

![Desktop screenshot](https://user-images.githubusercontent.com/9432032/68178756-729eeb80-ff8d-11e9-9a22-1a62f4fbe595.png)

If the response is a 1x1 px transparent gif: (In this case, if there was an place holder in CSS, the problem would be almost invisible to users.)

![Desktop screenshot](https://user-images.githubusercontent.com/9432032/68178886-de815400-ff8d-11e9-8684-1aa3ce622fd1.png)

**Comment by samdark** [comment]
So on error you want to return 1x1 px image with response code 200? I don't think it is a good idea. Would be extremely hard to find such error in logs. Server would pretend that it is normal.

**Comment by kamarton** [comment]
> So on error you want to return 1x1 px image with response code 200?

The status code can remain the original (5xx/4xx), just replace the content with to image + content-type.

**Comment by kamarton** [comment]
> If the response is a 1x1 px transparent gif: (In this case, if there was an place holder in CSS, the problem would be almost invisible to users.)

Screenshot created by HTTP 500 response.

**Comment by samdark** [comment]
Does that work for expected non-gif images to return empty gif?

**Comment by kamarton** [comment]
> Does that work for expected non-gif images to return empty gif?

It should not be a problem in browsers because Because HTML does not allow you to specify the desired image format (`<img>` tag), so `accepted: image / *` will be included in the request. 1x1 GIF is used because of its 24 byte size.

If an API endpoint were to generate the image, it could be a problem, but if the renderer is set to `image/*`, the output will always be correct.

**Comment by samdark** [comment]
OK. While it sounds like more or less specific use case I see no harm in supporting it.

**Comment by samdark** [comment]
Thought more about it.

1. It is not a job of error catcher.
2. It is specific use-case and should be implemented via try-catch in controller.
