### ISSUE TITLE
ErrorCatcher/HtmlRenderer: not migrated code in template

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#158]
I think the template was moved from yii2. There are problems with `$this` referencing and private functions in code of template.
```
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught Error: Using $this when not in object context in src/ErrorHandler/templates/exception.php:13
```

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
The template is alright. I've fixed the pull request in question.

**Comment by kamarton** [comment]
> The template is alright. I've fixed the pull request in question.

The template looks good but there is a bug somewhere, see #161.

**Comment by samdark** [comment]
I'll check it.
