### ISSUE TITLE
Emitter and streamed output

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/yii-web#165]
[We have a situation](https://github.com/yiisoft/yii-web/blob/22aaff78d9836f93561322bfacc3a4d852f0a0af/src/Emitter/SapiEmitter.php#L47) where the content of the stream are first completely unloaded into memory, and only then sent to the user.

The Emitter should output the stream in parts.

We should also consider supporting [HTTP Range Requests](https://tools.ietf.org/html/rfc7233#section-3).

**Comment by kamarton** [comment]
It should also be possible to disable this feature, as it is mostly not needed.

**Comment by roxblnfk** [comment]
I think that to send ranged Responses needed an individual Emitter, because for it to work correctly, we need to pass a Request object to it. And this is a different signature.

**Comment by samdark** [comment]
Why do we need request in an emitter?

**Comment by samdark** [comment]
Interface could be adjusted if needed.

**Comment by kamarton** [comment]
I suggest middleware instead of modifying the Emitter interface.

**Comment by roxblnfk** [comment]
> I suggest middleware instead of modifying the Emitter interface.

@smadark and i also came to this conclusion
