### ISSUE TITLE
Middlewares for response

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#166]
### What steps will reproduce the problem?

Yii2 was already able to manipulate the response (for example, adding a header) in the request object. It is often necessary to add headers globally to the response. The emitter is not suitable for this operation.

### What is the expected result?

Once the response has been generated, it is possible to specify a middleware chain that ensures manipulation for proper operation.

### What do you get instead?

Require to create custom emitter, or there is really no other solution to a uniform treatment.

### Use case

It is common for an API to require the request to be identified in the response, e.g. `Content-ID` header. This header should also appear in the response.

The development raised in the #165 issue could also be used. It is not Emitter's function to access the request object.
Middleware for this:
1. check request relevant headers
2. trim body
3. set response relevant headers

It can be insert in the middleware chain as needed.

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
There's such a middleware already (except it doesn't add headers): https://github.com/yiisoft/yii-web/blob/master/src/Middleware/TagRequest.php

Main middleware chain is already customizable: https://github.com/yiisoft/yii-demo/blob/master/src/Factory/MiddlewareDispatcherFactory.php

**Comment by kamarton** [comment]
aha

```php
class ContentId implements MiddlewareInterface {
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
 {
   return $handler->handle($request)->withHeader('content-id', $request->getHeader('content-id'));
  }
}
```
