### ISSUE TITLE
Add support of upload files from base64 encoded inputs

### ISSUE THREAD

**Issue by aminkt** [yiisoft/yii-web#17]
Hi.

Consider a case that you want upload a file in your yii2 rest api as json request. what should we do?
In some cases mobile developer send files in base64 encode format to server.
So i think yii2 should support this feature.

Like as `yii\web\UploadedFile` we will use something that extend this and implement base 64 or add this to current class.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13
| PHP version      | 7.1
| Operating system |windows

**Comment by aminkt** [comment]
I write a component to do this on
https://gitlab.com/aminkt/yii2-uploadManager-module/blob/master/classes/UploadedBase64File.php

**Comment by aminkt** [comment]
@samdark
If you think this is good please give me some comments to write thia part for yii community

**Comment by samdark** [comment]
@aminkt yes, it looks OK.

**Comment by aminkt** [comment]
Ok. like yii-rest is any repo to create a pull request or i use yii2?

**Comment by samdark** [comment]
This repo, I think.

**Comment by aminkt** [comment]
Ok. i will do.
Thanks
