### ISSUE TITLE
File response with webserver sending

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#172]
https://www.yiiframework.com/doc/guide/2.0/en/runtime-responses#sending-files
https://www.yiiframework.com/doc/api/2.0/yii-web-response#xSendFile()-detail

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
https://github.com/yiisoft/http#contentdispositionheader-usage
