### ISSUE TITLE
Response with attachment

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#174]
- yii2: https://www.yiiframework.com/doc/api/2.0/yii-web-response#$downloadHeaders-detail
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

### I suggests

Implementing to `HttpHelper`.

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
I'd suggest a separate class instead of putting it into a single large helper.

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii-web/blob/master/src/Cookie.php

**Comment by kamarton** [comment]
https://github.com/yiisoft/yii-web/pull/185#issuecomment-560321613

**Comment by kamarton** [comment]
```php
# RFC 2231/5987 Encoding: Character Sets
'2231iso' => ["filename=iso-8859-1''foo-%E4.html",null, null, ['filename' => 'foo-ä.html']],
'2231utf' => ["filename=UTF-8''foo-%c3%a4-%e2%82%ac.html",null, null, ['filename' => 'foo-ä-€.html']],
'2231noc' => ["filename=''foo-%c3%a4-%e2%82%ac.html", null,null, null, \InvalidArgumentException::class],

```

**Comment by rustamwin** [comment]
What about implement in [yiisoft/http](https://github.com/yiisoft/http)?

**Comment by sup-ham** [comment]
Maybe
- SendFile Middleware
- XSendFile Middleware

**Comment by samdark** [comment]
@sup-ham how do you plan to use middleware there?

**Comment by samdark** [comment]
https://github.com/yiisoft/http#contentdispositionheader-usage
