### ISSUE TITLE
Ability to specify custom templates for error handler HtmlRenderer

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#177]
There should be ability to specify custom template paths for HtmlRenderer.

- `exception` is for verbose mode.
- `error` is for production mode.

**Comment by strychu** [comment]
I've added additional parameters, but maybe it would be more elegant solution if custom path for renderers would be read from config file?

**Comment by xepozz** [comment]
Of course. Can you do it?

**Comment by strychu** [comment]
Ok, i'll work on that

**Comment by yiiliveext** [comment]
We already have the ability to add a custom error handler in the controller action.

**Comment by xepozz** [comment]
This enhancement will be applied to all controllers (I think so)

**Comment by samdark** [comment]
@yiiliveext it's about being able to provide your own templates such as https://github.com/yiisoft/yii-web/blob/master/src/ErrorHandler/HtmlRenderer.php#L38 without changing code of HtmlRenderer  itself.
