### ISSUE TITLE
SapiEmitter, additional cases for not sending content length

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#179]
If there's Transfer-Encoding header, 1xx, 204, 304 response code or when request type is CONNECT (we may ignore this one) - don't send Content-Length.

**Comment by kamarton** [comment]
I suggest replacing the `$withoutBody` parameter with the` $request` object parameter in the `EmitterInterface::emit()` method.

https://github.com/yiisoft/yii-web/blob/13b097a1afa6c1b18ac53ab1ef327bee3b929c45/src/Emitter/EmitterInterface.php#L12-L17

**Comment by samdark** [comment]
Why? It's not required for any of the conditions above.

**Comment by kamarton** [comment]
> Why? It's not required for any of the conditions above.

Could be a separate issue theme rather. If ignore the method condition, then obviously it would not be necessary. 

> when request type is CONNECT (we may ignore this one)

Defining the interface is weird, as it outsources the decision power from sapi to work properly with the data included in the request eg. HEAD or CONNECT methods. Instead, you have to rely on the `$withoutBody` parameter, which I don't know how it will function if, for example, I use my own non-standard method (eg API server LIST method).

**Comment by samdark** [comment]
Fixed by #175
