### ISSUE TITLE
Typed property Yiisoft\Yii\Web\User\User::$identity must not be accessed before initialization

### ISSUE THREAD

**Issue by thenotsoft** [yiisoft/yii-web#190]
Typed property Yiisoft\Yii\Web\User\User::$identity must not be accessed before initialization
when call Yiisoft\Yii\Web\User\User::isGuest()

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  7.4
| Operating system |

**Comment by thenotsoft** [comment]
fixed #191

**Comment by rob006** [comment]
How can you get this error, if this is not typed property (yet)?

**Comment by thenotsoft** [comment]
If you do not use typing, this error is absent, since the minimum version in the composer.json is now 7.4, I set the typing locally for the test and received an error.

**Comment by rob006** [comment]
So you just broken this class locally, a then reported this as a bug?...
