### ISSUE TITLE
Unable to display home page if running in subfolder and no trailing slash in url 

### ISSUE THREAD

**Issue by sup-ham** [yiisoft/yii-web#197]
### What steps will reproduce the problem?
Access with `http://localhost:8080/dev/yii-demo/public` (without trailing slash)

### What is the expected result?
Display normal homepage

### What do you get instead?
Displaying ```We were unable to find the page .```

### Additional info
- Using yii-demo in subfolder `/dev/yii-demo/public`
- Working properly if accessed with trailing slash

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 7.4
| Operating system | ubuntu

**Comment by samdark** [comment]
@roxblnfk would you please check this one?

**Comment by roxblnfk** [comment]
On my dev server it works good :-| I using Apache 2.4 (he automatically redirect to correct url)
I will make tests and fix this bug

**Comment by sup-ham** [comment]
I use php built-in server
