### ISSUE TITLE
counter based rate limiter

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-web#205]
### What steps will reproduce the problem?

GCRA is useful if the goal is that the minimum time between requests should not be less than specified. There are cases when peak is part of normal usage, so the goal is not to compliance the time between requests, but to limit the number of pieces within the specified interval.
For example:
Image upload on frontend where multiple images can be uploaded at once. In this case, the endpoint cannot be expected to require the time between uploads. The purpose of uploading in this case is the limits of normal use, eg. 30 images / 60s , and further restricted over a longer interval to eliminate unjustified uses, e.g. 100 images/ 300s.

### What is the expected result?

Peaks are also allowed.

### What do you get instead?

According to the example, it would take 1 minute to upload 30 images with the GCRA limiter.

### Additional info

It would be a good idea to create the simplest interface for middleware that is compatible with different limiter implementations.

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -
| Issue / PR | #204 #63

**Comment by samdark** [comment]
What's the purpose for limiting uploads in your case? To off-load the server?

**Comment by kamarton** [comment]
Primarily limiting normal use. It is possible to upload multiple images in parallel (javascript), but it is not allowed to flood the system with many images in the long run.

**Comment by samdark** [comment]
> It is possible to upload multiple images in parallel (javascript), but it is not allowed to flood the system with many images in the long run.

But that's exactly the case when it won't work. Server becomes overloaded when there is too much to process. In this case, uploads. It's usually bursts of processing tasks that are a problem, not regular constantly growing load that you can prepare for.

**Comment by kamarton** [comment]
> But that's exactly the case when it won't work. Server becomes overloaded when there is too much to process. In this case, uploads. It's usually bursts of processing tasks that are a problem, not regular constantly growing load that you can prepare for.

Burst is not a problem because it is served by multiple servers. 

How would you solve it with GCRA to upload 30 images within a reasonable amount of time, but not to upload more than 5000 images per month?

Not only that there are multiple algorithms, but you may have to use mixed ones. On a forum server you can limit it to 10 seconds per post (**GCRA**), but 5000 comments per month is far from normal (**counter based**), so it should be limited, notify to the administration, etc.

**Comment by samdark** [comment]
These are two separate concerns. One is rate-limiting requests to avoid peaks. Another is to impose a kind of business rule.

In case of rate-limiting it's a good idea to have a middleware for it. In case of business rule, I'd think twice and likely would do it right in the business logic code. The counter concept itself is similar though so yes, maybe part of it could be made reusable. Not sure it worth it though since simple counter is... simple enough to implement if needed.

**Comment by kamarton** [comment]
testing the current implementation, I came to the conclusion that it might be enough.
