### ISSUE TITLE
Pathinfo should not be decoded

### ISSUE THREAD

**Issue by iodragon** [yiisoft/yii-web#21]
In `yii\web\Request::resolvePathInfo()`, pathinfo has been decoded using `urldecode()`, which is similar in yii 1.x.

That would be an issue if the url path contains %2f.
For example a url path like `/foo/GNU%2fLinux/bar`, the pathinfo would become `/foo/GNU/Linux/bar`, which used for matching url rule. 
This may cause some problem when routing.

The code for resolving PathInfo is coming from Zend Framework, but the urldecode behavior has been added later, described in https://code.google.com/p/yii/issues/detail?id=1309
Zend Framework also fixed the similar issue in http://framework.zend.com/issues/browse/ZF-11017

Here are some test cases in Zend Framework for reference:
https://github.com/zendframework/zf1/blob/master/tests/Zend/Controller/Request/HttpTest.php#L988

**Comment by samdark** [comment]
PSR-7 is now used so this issue is not actual.
