### ISSUE TITLE
Is there a need for Chain middleware?

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#212]
Now that we have a middleware stacks for both router and general application, are there use-cases left for chain middleware?

@yiiliveext, @yiisoft/reviewers ?

**Comment by yiiliveext** [comment]
It may be useful to create another middleware that extends the Chain class but needs to be refactored.

**Comment by samdark** [comment]
It could be deleted since its main use-case was adding a stack of middleware to a route. But since then router is supporting it natively.
