### ISSUE TITLE
Implement AutoLoginMiddleware

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#218]
https://github.com/yiisoft/yii-web/blob/master/src/User/AutoLoginMiddleware.php

**Comment by mapeveri** [comment]
@samdark I would like work in this issue. I have some questions:

1. Right now it already implement the 'remember me' cookie?
2. As I understand if the cookie is there, I get the user and automatically login. Right?
3. Any documentation on how to login?.

Thanks!

**Comment by samdark** [comment]
1. No. There's `AutoLoginMiddleware` but it's empty.
2. Yes. See how it's done in Yii 2 about extra security measures:
  - https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L562
  - https://github.com/yiisoft/yii2/blob/master/framework/web/User.php#L584
  - etc.

**Comment by mapeveri** [comment]
@samdark 

1. OK
2. Great
3. I was referring mostly to how yii 3 login works
