### ISSUE TITLE
Additional tests for AutoLoginMiddleware

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#251]
- `testAddCookieAfterLogin()` - ensure that cookie header is present in response and is valid
- `testRemoveCookieAfterLogout()`  - ensure that cookie header is present in response and is valid

**Comment by strychu** [comment]
i can work on that

**Comment by strychu** [comment]
I've pushed second PR for a bug (i think) i found in AutoLoginMiddleware, provided tests will pass when #253 is merged
