### ISSUE TITLE
Cover ServerRequestFactory with tests

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-web#271]
and check that [this moment](https://github.com/yiisoft/yii-web/blob/54000c5e34d834efe61dce3ecd6ede36b86c31bd/src/ServerRequestFactory.php#L191) is working

**Comment by samdark** [comment]
@xepozz files are fine, we have these in yiisoft/app: https://github.com/yiisoft/app/blob/master/src/Contact/ContactMailer.php#L36
