### ISSUE TITLE
Too much unused private methods in HtmlRenderer

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-web#274]
[See example](https://github.com/yiisoft/yii-web/blob/54000c5e34d834efe61dce3ecd6ede36b86c31bd/src/ErrorHandler/HtmlRenderer.php#L106)

**Comment by samdark** [comment]
They are not unused. They are actually used in templates.

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii-web/blob/d7d5fb8eb58a0c5d976ac19016e1141eda87cb19/src/ErrorHandler/templates/exception.php#L417

**Comment by samdark** [comment]
Do you think there's a better way to do it?

**Comment by samdark** [comment]
Decided to make these methods public.
