### ISSUE TITLE
Separate package

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-web#275]
If you look at this package, you can find components that can be used outside the framework and the `yii-web` package.

I studied the question a bit and suggest the following actions:
1. <strike>Take out the cookie package.
    Classes for working with cookies are self-sufficient and can be reused in other projects. The only "parasitic" dependency is the `ResponseInterface` in the `CookieCollection`, but that’s not so scary.</strike>
2. <strike>Combine the `Session` and `Flash` components and put them into one package (`session`?)
    These two components are also self-sufficient and independent, and also, although this is hardly believed, can be reused outside the framework.</strike>
3. `Middlewares` folder
4. <strike>It would be nice to render `ErrorHandler` too.
    Now this dependency is needed only in `Application`. This component could potentially be used outside of the `yii-web` package. Moreover, the component also contains templates for rendering errors.</strike>
5. <strike>`Data`
    Response formatting is guaranteed to be used outside the framework. I think there’s no need to even discuss anything here. This is worth putting in a separate package.</strike>

**Comment by samdark** [comment]
@xepozz would that allow to slim down yii-web package so it will become suitable as dependency for API (yii-rest)?

**Comment by xepozz** [comment]
I think yes, it is. Furthermore yii-web can be really micro framework

**Comment by samdark** [comment]
5. https://github.com/yiisoft/data-response

**Comment by samdark** [comment]
Point 3 isn't a good one. Extracting all middleware in a single packages isn't good.

**Comment by roxblnfk** [comment]
About `CookieCollection`. 
What do you think about moving this to the `http` package?

**Comment by xepozz** [comment]
A good idea. I'm all for it.
Maybe move `Session` too?

**Comment by samdark** [comment]
Currently HTTP is mainly framework-independent and almost PSR-independent. The only place where PSR is used is `HeaderHelper::getSortedAcceptTypesFromRequest(RequestInterface $request)` and it likely worth removing this method (see https://github.com/yiisoft/http/issues/11).

We need to decide about the scope of this package:

1. Should it stay independent and represent HTTP RFCs only?
2. May it depend on PSRs? Which ones?
3. May it depend on the framework?

Based on answers we'll decide on cookies and session.

IMO, both cookies and session should either to stay in yii-web or be extracted in their own separate packages.

**Comment by samdark** [comment]
Decided to have separate repos for session / cookie.

**Comment by rustamwin** [comment]
- `User` folder -> [auth](https://github.com/yiisoft/auth)?

**Comment by rustamwin** [comment]
>We need to decide about the scope of this package:

1. I think no.
2. Maybe only `psr-http-message`.
3. It may depend on `di`.

**Comment by samdark** [comment]
@vjik extracted session and cookies.

**Comment by xepozz** [comment]
What about to extract User?

**Comment by samdark** [comment]
Isn't there a "user" concept in both API and web?

**Comment by xepozz** [comment]
I'm sorry I don't understand you.

**Comment by samdark** [comment]
Overall yes, extracting user is a good idea.

**Comment by samdark** [comment]
So far:

1. Need to move "user" part out. It should not hard-depend on session/cookies i.e. there could be an implementation with a token.
2. The package should not depend on session or cookies.

**Comment by xepozz** [comment]
@samdark can you please create the repo?

**Comment by samdark** [comment]
Done: https://github.com/yiisoft/user

**Comment by samdark** [comment]
@xepozz only point 3, "middlewares" left. What do you think about it? Which middleware are worth extracting?

**Comment by xepozz** [comment]
After a few discussions in telegram we have agreed to don't touch middlewares and leave it in `yii-web`.
`yii-web` now is clean base both for api and web projects.

So I think this issue should be closed. Good job :+1:

**Comment by samdark** [comment]
Thank you for preparing a great base for it.
