### ISSUE TITLE
Check if a param value matches the "int" param type in bindActionParams

### ISSUE THREAD

**Issue by djagya** [yiisoft/yii-web#28]
### What steps will reproduce the problem?

Using php7, have an action with the signature `public function actionIndex(int $count): string`.  
Visit the corresponding action url with a non-numeric `$count` param, e.g. `/site/index?count=test`. 

### What is the expected result?

I think a correct result should be a thrown `BadRequestHttpException` with a message `Invalid data received for parameter "{param}", expected type "{type}".`, same as it happens when an array url query param is specified for a non-array action method param, e.g. `public function actionIndex(string $name)` and the url `/site/index?name[0]=test&name[1]=test`.

Specifying action params types allows to avoid some errors (and strict typing is always better, right?), but I see an incorrect action method param we get from the url more as a user error (and therefore 400 or maybe 422) than a server error.

I guess `int` is the only important type we should check for, maybe `float` too. `boolean` doesn't require a check since any value can be casted to that type.

### What do you get instead?

`TypeError` server error `Argument 1 passed to ... must be of the type integer, string given`.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.?
| PHP version      | 7.1
| Operating system | macOS

**Comment by samdark** [comment]
Agree.

**Comment by djagya** [comment]
@samdark should I do that in this repository? We're talking about adding this feature to Yii2, right?

**Comment by kids-return** [comment]
You can implement it on this repo first, and yii2.0 no longer enhances new features.

**Comment by samdark** [comment]
@djagya No, Yii 2.0 isn't accepting features and this change is likely backwards incompatible.

**Comment by kids-return** [comment]
The minimum version of yii2.0 is php 5.4

**Comment by samdark** [comment]
Yes, that as well.

**Comment by samdark** [comment]
Related discussion: https://forum.yiiframework.com/t/action-parameter-binding/123992

**Comment by samdark** [comment]
Doesn't apply to current code/concepts.
