### ISSUE TITLE
Move error handler out of application

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#309]
We need to ensure that configuring of container is wrapped into error handler. Solution is to move error handler out of application into index.php.

**Comment by samdark** [comment]
The problem with it is that error handler is configured via container.

**Comment by mj4444ru** [comment]
Two error handlers are required. The first is easy to handle errors during the configuration creation phase. The second one is configurable to handle errors when the application is running.

**Comment by samdark** [comment]
Yeah. Something like that. Do you want to attempt solving it?

**Comment by mj4444ru** [comment]
I can suggest this option.
  - InternalServerError.php - Production.
  - InternalServerErrorDev.php - Output of debug information.

This code will also handle the exception if something went wrong in the main handler.
The user can freely customize the output by displaying, for example, a static branded page.

```php
if (!is_file($autoload)) {
    die('You need to set up the project dependencies using Composer');
}

require_once $autoload;

set_exception_handler(function(Throwable $exception) {
    $tpl = ini_get('display_errors') === '1' ? 'InternalServerErrorDev.php': 'InternalServerError.php';
    require dirname(__DIR__) . '/resources/' . $tml;
});
// Don't do it in production, assembling takes it's time
Builder::rebuild();
$startTime = microtime(true);
```

**Comment by samdark** [comment]
I wonder if we can create an instance of https://github.com/yiisoft/yii-web/blob/master/src/ErrorHandler/ErrorHandler.php right at the start of the file, call `register()`, init container, and then call `unregister()` after container is initialized so container's handler will take control.

**Comment by mj4444ru** [comment]
On a note

```php
    public function start(): void
    {
        $this->errorHandler->register();           <--- without unregister
        $this->eventDispatcher->dispatch(new ApplicationStartup());
    }

    public function shutdown(): void
    {
        $this->eventDispatcher->dispatch(new ApplicationShutdown());
    }
```

```php
    public function register(): void
    {
        $this->disableDisplayErrors();
        set_exception_handler([$this, 'handleThrowable']);
        set_error_handler([$this, 'handleError']);

        if ($this->memoryReserveSize > 0) {
            $this->memoryReserve = str_repeat('x', $this->memoryReserveSize);
        }
        register_shutdown_function([$this, 'handleFatalError']);           <-- Remains active after unregistrer.
    }

    public function unregister(): void
    {
        restore_error_handler();
        restore_exception_handler();
    }
```

**Comment by mj4444ru** [comment]
https://github.com/yiisoft/yii-web/blob/48861ce00acb6d25b3aa1d7173af3098fc549931/src/ErrorHandler/ErrorHandler.php#L70

Displaying the error as it is in production mode is bad.

**Comment by samdark** [comment]
> Displaying the error as it is in production mode is bad.

Yes, that should depend on https://github.com/yiisoft/yii-web/blob/master/src/ErrorHandler/ErrorHandler.php#L20

**Comment by samdark** [comment]
> On a note

Yes, that looks not correct.
