### ISSUE TITLE
Separate namespace in $_SESSION for flash messages

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii-web#31]
Currently the session component uses the "global" session namespace when setting messages:

```
* @param string $key the key identifying the flash message. Note that flash messages
* and normal session variables share the same name space. If you have a normal
* session variable using the same name, its value will be overwritten by this method.
* 
```

However there is also the `$flashParam` configuration.

```
/**
 * @var string the name of the session variable that stores the flash message data.
 */
 public $flashParam = '__flash';
```

Would it not make sense to store all messages inside `$_SESSION[$flashParam]['messages']` and move the counters to `$_SESSION[$flashParam]['counters']`?

Just like any name global namespace the session should be kept clean. The session is often part of the attack surface for a web application; reducing the global usage could reduce impact of incorrect usage.

It's a small change that won't affect anyone who is not writing / reading the session directly, which they should not any way.

PS. This is just something I feel could be a small improvement, I do have any usage issues with how it currently works, so if you disagree feel free to close this; no reason to have a lengthy discussion about it :)

**Comment by samdark** [comment]
https://forum.yiiframework.com/t/do-you-find-flash-messages-useful/126983

**Comment by SamMousa** [comment]
I use flash messages as a separate service. They can be stored in session, but could just as well be stored in cache or even persistent storage. By having a separate service / component that I inject into my actions I get better separation of concerns.

**Comment by SamMousa** [comment]
I'll post sample source later to give an idea
