### ISSUE TITLE
Rename @web to @baseUrl

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#312]
[`@web` alias](https://github.com/yiisoft/yii-web/blob/master/config/params.php#L14) should be renamed to `@baseUrl`. Needs to be done with search/replace in all other packages i.e. with `yii-dev-tool` fully deployed.

See https://trello.com/c/YqnPsZ3P/132-rename-web-alias-to-baseurl

**Comment by rustamwin** [comment]
See https://github.com/yiisoft/yii-web/commit/48861ce00acb6d25b3aa1d7173af3098fc549931
