### ISSUE TITLE
interface ApplicationParametersInterface

### ISSUE THREAD

**Issue by mj4444ru** [yiisoft/yii-web#314]
I propose the base class ApplicationParameters (using a special interface) and place a number of standard web applications so that third-party software (modules and extensions) could use it in the future.

```php
interface ApplicationParametersInterface
{
    public function get(string $name): string;

    public function getAdminEmail(): string;

    public function getCharset(): string;

    public function getEmail(): string;

    public function getInfoEmail(): string;

    public function getLanguage(): string;

    public function getName(): string;

    public function getSupportEmail(): string;

    public function has(string $name): bool;
}
```

This interface with its implementation will allow you to get any string parameters from the configuration without their preliminary description in the application parameters class.
By also extending this class in the application, we will be able to send data of any type and format (arrays and objects).
The standard implementation can work only with parameters of the type string deliberately, for strong typing.

**Comment by samdark** [comment]
I don't think it is a good idea:

1. There's no need for interface since it is unlikely to have more than a single implementation.
2. A third party service won't need all these parameters at once. Usually that's one or two parameters at max. For example, mailer will need support email or admin email only. A service should require what's needed, not where to get it.

**Comment by mj4444ru** [comment]
It was an alternative to the params array from yii2. Now I don't see anything like it.

**Comment by vjik** [comment]
> It was an alternative to the params array from yii2. Now I don't see anything like it.

You can use array `$params` (from config `params.php`) in container configuration (`common.php`, `web.php`, ...)

**Comment by samdark** [comment]
Direct access to $params isn't a good thing overall. Individual services should receive params needed at configuration time. `ApplicationParameters` is for parameters that don't have any service associates with them. These are usually used in views only.

**Comment by mj4444ru** [comment]
> Direct access to $params isn't a good thing overall. Individual services should receive params needed at configuration time. `ApplicationParameters` is for parameters that don't have any service associates with them. These are usually used in views only.

I generally thought about using this functionality exclusively in layout and view.

**Comment by samdark** [comment]
I think we'll stick with current solution for a while. We may reconsider it later.
