### ISSUE TITLE
Hyphens in module names

### ISSUE THREAD

**Issue by lmsmartins** [yiisoft/yii-web#32]
### What steps will reproduce the problem?
Create a module with camel case in the ID. E.g.: manageUsers 
The link should be:
"manage-users" instead of "manageUsers"
"manage-users/user/create" instead of "manageUsers/user/create"

### What is the expected result?
Module name in URL should contain hyphens instead of camel case words (just like controllers).

### What do you get instead?
Hyphens in the module name don't work.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.
| PHP version      | 7.0
| Operating system | Windows 10

**Comment by samdark** [comment]
There are no modules in 3.0.
