### ISSUE TITLE
Wrong response content

### ISSUE THREAD

**Issue by siamskoi** [yiisoft/yii-web#320]
### What steps will reproduce the problem?
1) Add middleware: FormatDataResponseAsJson::class
2) in controller: return $responseFactory->createResponse();

### What is the expected result?

We should get empty body in response

### What do you get instead?

But we get body with content-length = 4, and with content = null

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 7.4.9
| Operating system |Ubuntu 16.04.6 LTS

**Comment by samdark** [comment]
Fixed.
