### ISSUE TITLE
Get Yii version from Compose 2 API if available

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#321]
See https://getcomposer.org/doc/07-runtime.md. It could be used in https://github.com/yiisoft/yii-web/blob/master/src/Info.php.

**Comment by xepozz** [comment]
I have some questions:
1. Is `Info` really needed in yii-web?
2. Why [link refers to `yiisoft/app`](https://github.com/yiisoft/yii-web/blob/45350b60822f4c1f4d3ad11a0db0744ae66e353c/src/ErrorHandler/HtmlRenderer.php#L382)?

**Comment by samdark** [comment]
1. So far it's outputted at error page so when posting questions it's easier to specify concrete version.
2. That's temporary solution since Yii 3 isn't presented at yiiframework.com yet.

**Comment by xepozz** [comment]
Should it be moved to `ErrorHandler`?
In https://github.com/yiisoft/yii-web/issues/327 we can move `Info` also.

**Comment by samdark** [comment]
> Should it be moved to ErrorHandler?

Yes. I think so. We can also infer version from composer.lock or vendor dir if Composer API isn't available. Then we can avoid having it statically.

**Comment by rustamwin** [comment]
Can be closed favor of https://github.com/yiisoft/error-handler.

**Comment by xepozz** [comment]
Yes it's [already implemented](https://github.com/yiisoft/error-handler/blob/master/src/Info.php#L14)
