### ISSUE TITLE
Make AccessRule::matchIP() public.

### ISSUE THREAD

**Issue by vitalyspirin** [yiisoft/yii-web#35]
Make AccessRule::matchIP() public for external use (not to reimplement in user's code what's already implemented in framework). It would be convenient if it's static and list of ips is passed as parameter (instead of retrieving $this->ips). Therefore in allows() instead of 

https://github.com/yiisoft/yii2/blob/ec4509f21c2aa286fbb7aa2f258e561ece05ea38/framework/filters/AccessRule.php#L170

it would be 
` && static::matchIP($request->getUserIP(), $this->ips);`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.15.1?
| PHP version      | 7.1.23

**Comment by kamarton** [comment]
I don't know what the usage example is, but I think there is the `Ip` rule or `IpHelper` for this purpose. The use of `*` in IP addresses is not recommended, not least because in IPv6 it is not specified whether the string will be in full or minimal form.

```php
    /**
     * @var array list of user IP addresses that this rule applies to. An IP address
     * can contain the wildcard `*` at the end so that it matches IP addresses with the same prefix.
     * For example, '192.168.*' matches all IP addresses in the segment '192.168.'.
     * If not set or empty, it means this rule applies to all IP addresses.
     * @see Request::userIP
     */
    public $ips;
```

**Comment by samdark** [comment]
@kamarton the use case is checking if current user IP is within configured range or mask. That's for access control such as Gii.

**Comment by samdark** [comment]
And yes, `IpHelper::inRange()` does the job. Thanks for pointing it out.
