### ISSUE TITLE
Question : Event AfterRequest and throw exception

### ISSUE THREAD

**Issue by ncou** [yiisoft/yii-web#365]
Hi,

Nice piece of code. Looking at the Request events part in the code i have a question.

Line : https://github.com/yiisoft/yii-web/blob/master/src/Application.php#L58
Why don't you add a try/finaly around the dispatcher to ensure the event AfterRequest is triggered even when there is an throw exception ?

Like what is done in the AfterMiddleware event. https://github.com/yiisoft/yii-web/blob/master/src/Application.php#L58

Keep up the good work.

**Comment by samdark** [comment]
Good idea. Thanks.

**Comment by ncou** [comment]
Thank you.

Didn't do the test, but shouldn't the typehint in the AfterRequest::class now be "?ResponseInterface" to allow a null value in the event (in case there is an error).

**Comment by samdark** [comment]
Right. https://github.com/yiisoft/yii-web/commit/28b6019f73311a8a19a16fa60afcbb8a88bf4c3c
