### ISSUE TITLE
Assets preload

### ISSUE THREAD

**Issue by degibons** [yiisoft/yii-web#368]
This is just a proposal for discussion of assets preload (https://www.w3.org/TR/preload/).  

I've not found any mechanism to implement this option in the current framework release (nothing in View, AssetManager or AssetBundle). Maybe it will make sense to add this option in the future releases? (maybe, something like the other frameworks did, for example https://goo.gl/DH1Ymt)

**Comment by samdark** [comment]
Doesn't apply to current code/concepts.
