### ISSUE TITLE
Add support PHP web server

### ISSUE THREAD

**Issue by andrew-svirin** [yiisoft/yii-web#369]
Hi!
Where can i find command `yii serve` like it is in Yii2?

**Comment by rustamwin** [comment]
See [yiisoft/app](https://github.com/yiisoft/app), [yiisoft/demo](https://github.com/yiisoft/demo) there is also a `yii serve` command there.

**Comment by andrew-svirin** [comment]
Thanks! Good puzzle. I can not guess where the Serve file is locating. Probably it is not a good idea to use Yii3 today.

**Comment by andrew-svirin** [comment]
https://github.com/yiisoft/app/blob/master/composer.json - this file does not contains yiisoft/yii-console dependency, but in rREADME file mentioned command `yii serve`

**Comment by vjik** [comment]
> https://github.com/yiisoft/app/blob/master/composer.json - this file does not contains yiisoft/yii-console dependency, but in README file mentioned command `yii serve`

Good point. I'm create PR: https://github.com/yiisoft/app/pull/168
