### ISSUE TITLE
Setting unknown property: yii\web\Application::requestedRoute

### ISSUE THREAD

**Issue by philippfrenzel** [yiisoft/yii-web#51]
### What steps will reproduce the problem?
git clone https://github.com/philippfrenzel/weasy.git
docker-compose up -d
localhost:8010

### What is the expected result?
yii error log Setting unknown property: yii\web\Application::requestedRoute

### What do you get instead?
website

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 3@dev
| PHP version      | official docker image yii3
| Operating system | official docker image yii3

**Comment by razonyang** [comment]
Maybe it  is because yiisoft/yii-core#47 and yiisoft/yii-core#172

**Comment by philippfrenzel** [comment]
yes, looks like you are right - but if I have debug on - it seems like these fields are mandatory... hmm how can I fix it - for know I can remove the logger...?

**Comment by philippfrenzel** [comment]
can be closed for now as @hiqsol reverted the commit which removed additional variables
