### ISSUE TITLE
Same-site Cookies support (new feature discusion)

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii-web#61]
"Same-site cookies allow servers to mitigate the risk of CSRF and information leakage attacks by asserting that a particular cookie should only be sent with requests initiated from the same registrable domain."

Same-site cookies are implemented in Chrome, coming to Mozilla, and on standard track at IETF.

- [Chrome Platform Status: 'SameSite' cookie attribute](https://www.chromestatus.com/feature/4672634709082112)
- [Same-Site Cookies IETF WG Draft](https://datatracker.ietf.org/doc/draft-ietf-httpbis-cookie-same-site/)
- [Bugzilla: Add SameSite support for cookies](https://bugzilla.mozilla.org/show_bug.cgi?id=795346)

PHP apps can set same-site cookies by setting the `Set-Cookie` HTTP header. It seems likely that support for same-site cookies (i.e. an API making it easier to set same-site cookies) will be built into PHP 7.3.

- [PHP RFC: Same Site Cookie](https://wiki.php.net/rfc/same-site-cookie)
- [Internals: [RFC] samesite cookie implementation](https://externals.io/message/99884)
- [Internals: [VOTE] Same Site Cookie RFC](https://externals.io/message/100304)

If, as a developer using `yii\web\Cookie`, I want to set same-site, it makes sense to do it through that API. So I suggest we consider adding it.

I also wonder if it is desirable to add it to Yii's implementation of sessions.

**Comment by lukebailey** [comment]
Is there any update on when this will be implemented?

**Comment by samdark** [comment]
No. All the updates are posted right there in the issue comments.

**Comment by lukebailey** [comment]
Is this a low priority so we can set expectations? It seemed like you guys were close to adding it over a year ago

**Comment by samdark** [comment]
It will be added to Yii 3 before release but right now it's a low priority compared to assembling everything else. It won't be added to Yii 2.

**Comment by samdark** [comment]
It was added to 2.0: https://github.com/yiisoft/yii2/commit/1ed6ec1e5cdcd0bacbda67a129efa1aa88648d66 and released.

For 3.0 it is now very high priority for now.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-web/commit/103751788b9d11a07d93f46dd70db34bf00f0c3a
