### ISSUE TITLE
jsonp response doesn't display error information.

### ISSUE THREAD

**Issue by takashiki** [yiisoft/yii-web#62]
### What steps will reproduce the problem?

When `$repsonseFormat` is set to `Response::FORMAT_JSONP`, any exceptions will occur this problem.

### What is the expected result?

Erorr infomation formatted to jsonp.

### What do you get instead?

An empty 500 response.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.9
| PHP version      |7.0.11
| Operating system |CentOS 6.5

### Cause

Member function `renderException` in `\yii\web\ErrorHandler`  didn't process `$process->data` for `jsonp` format.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/11529

**Comment by kamarton** [comment]
Accessing the callback name may be a problem here.

**Comment by samdark** [comment]
@kamarton ?

**Comment by samdark** [comment]
For now we decided not to implement JSONP.
