### ISSUE TITLE
The suggestion to Yii2 core team is to design RateLimiter filter good enough not only for API calls, but to make it more reusable in simple controllers.

### ISSUE THREAD

**Issue by gauravpatel1110** [yiisoft/yii-web#63]
Here is the use case:

    Limit number of API calls globally - 5 requests/second
    Limit number of API calls for action1 - 30 requests/minute
    Limit number of API calls for action2 - 60 requests/minute

    Limit number of successfull user registrations (action /register) - 1/hour
    Limit number of failed user logins (action /login) - 5 requests/15 minutes
    Add possibility to have 1 shared limit for several actions

  Make This With FileCache.

**Comment by samdark** [comment]
Rate limiter should be implemented as middleware.

**Comment by kamarton** [comment]
I would recommend separate the actual counting unit and using it anywhere in the code, eg sending SMS limit.

**Comment by samdark** [comment]
This one is now done.
