### ISSUE TITLE
AJAX mode redirection logic is not RFC conform

### ISSUE THREAD

**Issue by MainAero** [yiisoft/yii-web#64]
The current implementation of redirection logic in AJAX mode is not RFC conform.
In [RFC 1945](https://tools.ietf.org/html/rfc1945#section-9.3) under `302 Moved Temporarily`  it says: `The URL must be given by the Location field in the response.` In [RFC 2616](https://tools.ietf.org/html/rfc2616#page-62) the polite version of it: `The temporary URI SHOULD be given by the Location field in the response.`

In my case I using [axios](https://github.com/axios/axios) as http client in my ReactJS app. When I request a action on my Yii2 app which response with a redirect the request will fail. The axios library expects to see a `Location` header when getting a `302` status code.

As I think that Yii2 is not RFC conform I decided to raise here an issue.

Should I provide a PR for that?
The affected line is [this](https://github.com/yiisoft/yii2/blob/master/framework/web/Response.php#L857) one.

### What steps will reproduce the problem?
Consider you have a actions like this:
```php
...
public function actionIndex()
{
   Yii::$app->response->format = 'json';
   return $this->redirect(['site/login']);
}
...
```
Request it in AJAX mode:
```bash
curl -H "X-Requested-With: XMLHttpRequest" -I http://localhost/
```
### What is the expected result?
```bash
...
HTTP/1.1 302 Found
Location: http://localhost/login
...
```
### What do you get instead?
```bash
...
HTTP/1.1 302 Found
X-Redirect: http://localhost/login
...
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.13.1
| PHP version      | 7.2.1
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
We don't have it in Yii 3. Can't be applied to current code.
