### ISSUE TITLE
Bug in logic setReturnUrl() in a multi domains project

### ISSUE THREAD

**Issue by voskobovich** [yiisoft/yii-web#65]
If guest go to `backend.domain.com/user/1` the system will require authorization and will forward on `account.domain.com/auth/login`. But after login, the user will be redirected to `account.domain.com/user/1` and will see an error page.

Here is my solution:
https://github.com/voskobovich/yii2/commit/ea469e08fc6b613825b2fa3f83bd68019c34cdda

**Comment by alex-code** [comment]
Just noticed this, fixed in Yii2 with [#17446](https://github.com/yiisoft/yii2/pull/17446) but'll need porting across.

**Comment by samdark** [comment]
Can't be applied to current code.
