### ISSUE TITLE
Missing support for the Content Security Policy Header 

### ISSUE THREAD

**Issue by bicf** [yiisoft/yii-web#66]
Due missing of CSP in Yii2 I develop a basic support of CSP.

Following the "Git workflow for Yii 2 contributors" I open this issue.

**Comment by samdark** [comment]
There's https://github.com/middlewares/csp we can use right away.

**Comment by samdark** [comment]
Closing for now. Will consider our own if the one above won't work well.

**Comment by bicf** [comment]
Hi,

I like very much the PSR-7 implementation of [https://github.com/middlewares/csp](https://github.com/middlewares/csp)  but how is the integration of PSR-7 in yii2?

[https://github.com/paragonie/csp-builder](https://github.com/paragonie/csp-builder) has a strong approach on generating HASH by "scanning" the sources (CSS, JS) directories but this approach need at least one more step (regenerate the hashes) after an _update_ by composer or any changes in the JS/CSS files.  

Futhermore this approach do not allow the _nonce signature_, "only" to send the CSP header, and that's a big limitation when you cannot trust _self_ because a carrier or a virus inject a malicious JS in your pages.

I've refactored my [yii2-security-headers](https://github.com/bicf/yii2-security-headers) now it has a smaller footprint and a better documentation. I think it could be more effective with a PSR-7 + PSR-15 implementation and optionally integrate the [https://github.com/paragonie/csp-builder](https://github.com/paragonie/csp-builder) so I'm hope in a quick response about the PSR-7 integration in yii.

**Comment by samdark** [comment]
> how is the integration of PSR-7 in yii2?

There won't be any integration of PSR-7 into Yii 2. It is Yii 3 only.
