### ISSUE TITLE
Routing Redirect

### ISSUE THREAD

**Issue by KnightYoshi** [yiisoft/yii-web#68]
Would you consider adding to urlManager 301/302 redirect support for the rules. This way it doesn't have to go to a controller/action of something like a deprecated path to be redirected by that action.
```
[
   'pattern' => 'some/old/route/',
   'redirect' => 'some/new/route/', // could accept parameters like how the route prop does
   'statusCode' => 301 // optional, but defaults to 301
]
```

**Comment by samdark** [comment]
In the current paradigm it could be done either via introducing custom syntax or via introducing Redirect middleware. I'm leaning towards middleware. May look like this:

```php
Route::get('/test1')->to(Redirect::toUrl('https://yiiframework.com/')),
Route::get('/test2')->to(Redirect::toRoute('anotherRouteName'))),
```
