### ISSUE TITLE
Encrypt and validate session and/or cache data?

### ISSUE THREAD

**Issue by tom--** [yiisoft/yii-web#70]
**Feature idea**

Data is vulnerable to theft and modification while it is at rest in a cache or session store and while it is in transit between PHP and that store. Users can reduce vulnerability with cryptographic validation to detect tampering or with encryption+validation incorporated into session/cache read and write handling.

I think Yii could support for these functions so that they are relatively easy to use. The user should need to do little more than configure it and provide a function that returns a key within a specific context (e.g. session context).

**Comment by samdark** [comment]
Extension points are still there. Not going to add encryption out of the box for now.
