### ISSUE TITLE
yii\web\User dependend from Yiisoft\Rbac\CheckAccessInterface

### ISSUE THREAD

**Issue by Insolita** [yiisoft/yii-web#71]
yii\web\User require implementation of Yiisoft\Rbac\CheckAccessInterface so it force us to install yii-rbac package even we don't want to use it. Also yii-web has'nt yii-rbac as production dependency, so seems something wrong

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 3.0@dev

**Comment by SamMousa** [comment]
I think the implementation https://github.com/yiisoft/yii2/blob/master/framework/rbac/CheckAccessInterface.php

Should be moved to the core package in yii3; possibly in some kind of `contracts` or `interfaces` namespace.

**Comment by samdark** [comment]
I'd suggest `yiisoft/access`.

**Comment by SamMousa** [comment]
@samdark what else would go there?
Does it not make more sense to gather contracts that are used by the core (even if it comes with no implementations) in a `contracts` namespace? (Note i'm not sure that this specific interface is used by the core)

**Comment by samdark** [comment]
Nothing.

> Does it not make more sense to gather contracts that are used by the core (even if it comes with no implementations) in a contracts namespace?

No. That's what Symfony/Laravel did previously. I was slightly grumpy about it there so Symfony is splitting now: https://github.com/symfony/symfony/issues/31567

**Comment by SamMousa** [comment]
Ah, that makes sense!

**Comment by samdark** [comment]
https://github.com/yiisoft/access/issues/1

**Comment by samdark** [comment]
Done.
