### ISSUE TITLE
CSRF as middleware?

### ISSUE THREAD

**Issue by rustamwin** [yiisoft/yii-web#77]

**Comment by samdark** [comment]
Yes.

**Comment by terabytesoftw** [comment]
This middleware works well to generate the CSRF, but we need to have a Session Middleware, there will be an official one or one must be used for now use.

```
https://github.com/odan/session
https://github.com/odan/csrf
```

Any official suggestions,

Thks,

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-web/issues/87

**Comment by samdark** [comment]
Session is done including a middleware.

**Comment by terabytesoftw** [comment]
I managed to implement the CSRF token with a middleware, the bad thing about all the packages is that there must be an open session to pass the id, while I try it in this way but it would seem that I do a hacking, as we could implement it by saving it in the session, with the meta tags, or in a cokkie, will be extending the session middleware, which you think would be the best way.

```
    CsrfMiddleware::class => function (ContainerInterface $container) {
        $session = $container->get(SessionInterface::class);

        // The CSRF middleware requires a valid session id
        if (!$session->isActive()) {
            $session->open();
        }

        $csrf = new CsrfMiddleware(new Psr17Factory(), $session->getId());
        $session->set('_csrf', $csrf->getToken());

        return $csrf;
    },
```

**Comment by samdark** [comment]
Session is automatically opened if you are trying to read/write from it so there's no need for explicit check.

Can't we require Session and PSR-17 factory as dependencies of CsrfMiddleware? Then there will be no need for complicated initialization.

**Comment by rustamwin** [comment]
Logic should be ported from Yii2 ?

**Comment by samdark** [comment]
Partially. Overall that would be kind of different because there were no middleware in 2.0.

**Comment by rustamwin** [comment]
Sent PR #103

**Comment by terabytesoftw** [comment]
> Session is automatically opened if you are trying to read/write from it so there's no need for explicit check.
> 
> Can't we require `Session` and PSR-17 factory as dependencies of `CsrfMiddleware`? Then there will be no need for complicated initialization then.

And in which part of the code can I access the session already open?

**Comment by samdark** [comment]
1. You don't have to take care if it is open or not. Just read from it or write into it. It will open automatically.
2. You can access session anywhere via type-hinting. It is stored in DI container and will be injected.

**Comment by rustamwin** [comment]
> And in which part of the code can I access the session already open?

in constructor
