### ISSUE TITLE
Port error views

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#78]
[Skeleton for error rendering is done](https://github.com/yiisoft/yii-web/commit/5906cf7f7b3a24ad9836f05bd5f779f6621999c1). Rendering itself should be ported from Yii 2.0:

- [x] HTML
- [x] JSON
- [x] XML
- [x] PlainText (used for logs as well)

Could be tested by installing [yii-demo](https://github.com/yiisoft/yii-demo) via [yii-dev](https://github.com/yiisoft/yii-dev).

**Comment by cebe** [comment]
For JSON format it would be good to follow a standard, e.g. "Problem Details for HTTP APIs" https://tools.ietf.org/html/rfc7807

**Comment by samdark** [comment]
Wasn't aware of this RFC. Thanks!

**Comment by samdark** [comment]
It's describing XML as well.

**Comment by samdark** [comment]
@cebe checked the RFC and I think it's not suitable for generic errors.
