### ISSUE TITLE
[yii\base\Request] should have $id field

### ISSUE THREAD

**Issue by mikk150** [yiisoft/yii-web#8]
### What steps will reproduce the problem?
Currently if looking at log output that generates thousands of lines per second it is really hard(read: not possible) to distinguish which lines belong to what request

### What is the expected result?
each request should have unique identifier(could be UUID, huge random number or whatever) which users can use to distinguish different requests to write log or whatever they want

### Additional info

Log output could put this unique identifier before data so that people can distinguish different requests

**Comment by samdark** [comment]
That could be useful to display this ID to end users as well such as https://en.rmcreative.ru/blog/youtubes-500-error-page/

**Comment by samdark** [comment]
The following ID should be enough for such use case:

```php
dechex(microtime(true) * 1000000);
```

**Comment by samdark** [comment]
Having it in log could be useful for `grep`ing.

**Comment by mikk150** [comment]
@samdark you can move this from yii-web to yii-core as same problem is with console application

currently trying to get a solution with this
```php
base64_encode(pack('ia*', time(), Yii::$app->security->generateRandomString(10)));
```

because I am going to end up with n+1 application running simultaniously, I can get collision that way

**Comment by rob006** [comment]
> The following ID should be enough for such use case:
> 
> ```
> dechex(microtime(true) * 1000000);
> ```

It makes more sense to use `uniqid()` by default. And add option to easily use different algorithm (for example `ramsey/uuid`).

**Comment by mikk150** [comment]
> > The following ID should be enough for such use case:
> > ```
> > dechex(microtime(true) * 1000000);
> > ```
> 
> It makes more sense to use `uniqid()` by default. And add option to easily use different algorithm (for example `ramsey/uuid`).

http://php.net/manual/en/function.uniqid.php

```
Warning This function does not guarantee uniqueness of return value
```
