### ISSUE TITLE
Easy bound controller middleware

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#84]
# Goal

Embrace convention for controller routes to simplify RAD-style development.

# Idea

```php
$router->addRoute(Route::any('/site/{action}')->to(new WebActionsCaller(SiteController::class));
```

That would route any URL that starts with `/site` to a method of `SiteController` named `{action}` i.e. `/site/index` would be routed to 

```php
class SiteController
{
    public function site()
    {
    }
}
```

# Issues

1. Unable to handle URLs like `site/update/{id}` because router needs to know all the parameters beforehand. In Yii 2 such cases required separate route anyway, so could be left as is.

**Comment by terabytesoftw** [comment]
Please add example,

thks,
