### ISSUE TITLE
PHP Warning: ini_set() has been disabled for security reasons

### ISSUE THREAD

**Issue by rebill** [yiisoft/yii-web#89]
PHP Warning: ini_set() has been disabled for security reasons in `/vendor/yiisoft/yii2/base/ErrorHandler.php` on line 60

```php
public function register()
{
        ini_set('display_errors', false);
        // ......
}
```
can add `@` to ignore warning error ? 

```php
public function register()
{
        @ini_set('display_errors', false);
        // ......
}
```

**Comment by samdark** [comment]
- https://www.php.net/manual/en/function.ini-get-all.php
- https://www.php.net/manual/en/configuration.changes.modes.php#configuration.changes.modes
