### ISSUE TITLE
Add curl command to error page

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#90]
See https://forum.yiiframework.com/t/error-handler-is-back/126667/2?u=samdark

**Comment by alexkart** [comment]
@samdark , I want to write a library `curl-builder` that builds curl commands. Is it ok to use it in `yii-web` or the library must be in the `yiisoft`? See example https://github.com/yiisoft/yii-web/pull/94

**Comment by samdark** [comment]
It is fine as long as you plan maintaining it properly?

**Comment by samdark** [comment]
Well, not if it does what it currently does. It doesn't worth relying on external dependency for just https://github.com/alexkart/curl-builder/blob/master/src/Command.php

**Comment by alexkart** [comment]
Of course, currently, it's just an example.

**Comment by samdark** [comment]
Let's see how it goes. If it will have complicated logic that is usable separately — it's fine. If it will be simple enough, I'd prefer not to having another dependency.

**Comment by alexkart** [comment]
Agreed, if it ends up being small I'll add the code directly to `yii-web`.

**Comment by alexkart** [comment]
@samdark, so, I've finished the first version of the library, you can check it here https://github.com/alexkart/curl-builder. Is it good enough to add it to the `yii-web` as a dependency?

**Comment by samdark** [comment]
Yes. I've sent a pull request: https://github.com/alexkart/curl-builder/pull/2
