### ISSUE TITLE
Should error handler pass errors to standard PHP log?

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#92]
In Yii 2 errors processed with error handler aren't passed to PHP error log. I wonder if we should keep that behavior or start logging errors additionally with PHP error log.

**Comment by rob006** [comment]
Why would you want to have them in PHP error log? Yii 2 error handler is much powerful. For me PHP error log is more like a last resort - it is used only if something really bad happened and Yii was not able to handle it.

**Comment by evil1** [comment]
Abesolutely true! Yii logs should NOT pass anything to PHP error log.
