### ISSUE TITLE
Ability for error handler to be switched to non-verbose mode

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-web#93]
Useful for production where you don't want stack traces and details exposed.

**Comment by samdark** [comment]
Could be ported from Yii 2.

**Comment by kamarton** [comment]
@samdark Is this the ticket for such cases? or is it completely different?

https://github.com/yiisoft/yii-web/blob/master/src/ErrorHandler/JsonRenderer.php

**Comment by samdark** [comment]
It is for all cases we have: web, xml, json.
